### ISSUE TITLE
How to download without proxy（如何不使用代理进行下载）

### ISSUE THREAD

**Issue by cy920820** [CWHer/PixivCrawler#2]
![image](https://user-images.githubusercontent.com/21211512/189834695-0ab8ed7c-13bc-4071-bfd9-a9b083b4804e.png)

**Comment by cwher** [comment]
但是国内不用代理确实上不去啊🤔会 Fail 不是很正常吗

**Comment by cy920820** [comment]
公司内网直接走的香港代理，所以本地并没有开启任何代理，请求如何绕开代理配置？

**Comment by cwher** [comment]
你直接访问这个网址能正常加载吗？

正常的结果如下图所示

![image](https://user-images.githubusercontent.com/31888981/190092686-b2afecb1-06f6-418a-aa7e-a7138ae46f66.png)

**Comment by cy920820** [comment]
> 你直接访问这个网址能正常加载吗？
> 
> 正常的结果如下图所示
> 
> ![image](https://user-images.githubusercontent.com/31888981/190092686-b2afecb1-06f6-418a-aa7e-a7138ae46f66.png)

可以访问

**Comment by cwher** [comment]
> 请求如何绕开代理配置？

~~我好像之前误解你的意思了~~，不需要走代理的话，在`config`里配置

```python
NETWORK_CONFIG = {
    "PROXY": None,
    ...
}
```

我试了下这样似乎可以不使用代理，这确实是一个 corner case

**Comment by cy920820** [comment]
> > 请求如何绕开代理配置？
> 
> ~我好像之前误解你的意思了~，不需要走代理的话，在`config`里配置
> 
> ```python
> NETWORK_CONFIG = {
>     "PROXY": None,
>     ...
> }
> ```
> 
> 我试了下这样似乎可以不使用代理，这确实是一个 corner case

配置了，请求可以发出去了，但是又报错了：

![image](https://user-images.githubusercontent.com/21211512/191203521-08e684f1-f8d2-42e2-9591-e5d86e9c691a.png)

**Comment by cwher** [comment]
将`config.py`中的`WITH_TAG`设置成`false`试试
