### ISSUE TITLE
Returning image URLs instead of downloading images

### ISSUE THREAD

**Issue by KuroganeToyama** [CWHer/PixivCrawler#24]
I'm wondering if it's possible to implement a method that instead of downloading images, would simply collect the source URL of each image collected. This would be really useful, as people (and me 😅 ) could use that to integrate this crawler into developing our own APIs, while still respecting the artists. 

I had this thought because I wanna be able to use your tool to let the Discord bot do some more fun for the little server of me and my friends 😅 

I think (very subjective statement here) that this feature should be not too hard, from my glance at the source code, but do correct me if I'm wrong 😅

**Comment by cwher** [comment]
Will be done this week.

**Comment by KuroganeToyama** [comment]
Thanks a lot! I'd also really appreciate if you could give me update when you've implemented the feature. But if you do hit a block, do update me as well, and maybe I could be of some help. Thanks again! 😁

**Comment by cwher** [comment]
- `download_config.url_only: bool`: Whether to download image URLs only, without downloading images. URL will be returned through `app.run()`. :warning:

    ```python
    ...
    download_config.url_only = True

    ...
    urls = app.run()  # a set of image URLs
    ```

**Comment by cwher** [comment]
PyPI version will be updated soon.

**Comment by KuroganeToyama** [comment]
Hi there, thank you so much for the hard work! I took a look through the repo and it looked great! I'll wait for the updated package. Once again, thanks a lot!

**Comment by cwher** [comment]
The new version v1.0.1 has been released to PyPI.

**Comment by KuroganeToyama** [comment]
The package is working great! Thank you so much for all the work 😄
