### ISSUE TITLE
[Feature Request] filter out AI generated artworks

### ISSUE THREAD

**Issue by akichannnnn** [CWHer/PixivCrawler#7]
add the option to allow users to filter out ai generated artworks

**Comment by cwher** [comment]
~~我认为最简单的做法是同时下载图片和标签，之后再手动根据标签删一下下载完的图片~~

我大概看了一下，`AI生成`主要是标签上的差异，不下载标签也区分不出来，下载了标签的话还是本地再手动删除方便（
