### ISSUE TITLE
特定标签什么都没下载就结束了

### ISSUE THREAD

**Issue by 841003695** [CWHer/PixivCrawler#8]
如图。不加tag时可以下载，但下载的不知道都是些什么。加了角色的标签后就变成这样了。之前那一台电脑可以用，换了台就不行了。问题出在哪？
<img width="1280" alt="屏幕截图 2023-07-13 200820" src="https://github.com/CWHer/PixivCrawler/assets/42113805/8d24703f-9162-49da-a4bf-150d8187f715">

想下载的是这个https://www.pixiv.net/tags/%E7%94%9F%E5%A1%A9%E3%83%8E%E3%82%A2/illustrations?s_mode=s_tag&type=illust

**Comment by cwher** [comment]
把括号去掉试试

```python
app = KeywordCrawler(keyword="生塩ノア",
                     order=False,
                     mode=["safe", "r18", "all"][-1],
                     n_images=20,
                     capacity=200)
```

**Comment by 841003695** [comment]
可以了，感谢
