### ISSUE TITLE
下载pid

### ISSUE THREAD

**Issue by 1314000** [CWHer/PixivCrawler#9]
大佬，怎么样可以只下载个人收藏的图片pid，而不用下载图片ヾ(•ω•`)o

**Comment by cwher** [comment]
这个功能可以支持，但得改代码，你打算自己改一下吗🧐

**Comment by 1314000** [comment]
> 这个功能可以支持，但得改代码，你打算自己改一下吗🧐

小白一个😭存了五年的图图，结果U盘坏了，现在想拿pid比对一下

**Comment by cwher** [comment]
我下班改改

**Comment by 1314000** [comment]
> 我下班改改

谢谢佬🥳

**Comment by cwher** [comment]
![image](https://github.com/CWHer/PixivCrawler/assets/31888981/c5972603-35c5-4832-aa5c-341973f35ea1)
你把代码这样改一下，再用`BookmarkCrawler`就好了

**Comment by 1314000** [comment]
OK，我试试

**Comment by 1314000** [comment]
成了🥳，能支持大佬一杯奶茶吗

**Comment by cwher** [comment]
没事，点个🌟就可以了🥳

**Comment by 1314000** [comment]
> 没事，点个🌟就可以了🥳

早就点了😂
